services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d

volumes:
  data:
    driver: local